name: "Deploy Jekyll to GitHub Pages"

on:
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual
  push:
    branches:
      - main  # Jalankan saat ada perubahan di cabang 'main'

permissions:
  contents: read  # Mengizinkan membaca repositori
  pages: write    # Mengizinkan menulis ke GitHub Pages
  id-token: write # Required for deploying to GitHub Pages

concurrency:
  group: "pages"
  cancel-in-progress: false  # Tidak membatalkan workflow yang sedang berjalan

jobs:
  build:
    runs-on: ubuntu-latest  # Jalankan di lingkungan Ubuntu terbaru

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mengambil kode dari repositori
      
      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Versi Ruby yang digunakan

      - name: Install dependencies
        run: |
          gem install jekyll bundler  # Instal Jekyll dan Bundler
          bundle install  # Instal semua dependensi di Gemfile (jika ada)

      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build  # Bangun situs Jekyll ke dalam folder '_site'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Mengunggah hasil build
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Pastikan build selesai sebelum deploy

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
