name: "ESLint and SARIF Upload"

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 15 * * 3'

jobs:
  lint:
    name: "Run ESLint Analysis"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          mkdir -p reports
          node_modules/.bin/eslint build docs lib script spec-main \
          -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js \
          -o reports/eslint-results.sarif || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-results.sarif
          category: eslint

  test:
    name: "Run Jest Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test

  format:
    name: "Run Prettier"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: |
          mkdir -p reports
          npx prettier --check "src/**/*.js" > reports/prettier-results.txt || true

      - name: Upload Prettier results
        uses: actions/upload-artifact@v2
        with:
          name: prettier-results
          path: reports/prettier-results.txt
